spring:
  application:
    name: user
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 18881

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://root:root@localhost:18880/eureka/
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
#  打印sql语句到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
THREAD:
  NAME: t
#seata:
#  enabled: true
#  application-id: rb_user
#  enable-auto-data-source-proxy: true
#  tx-service-group: my_test_tx_group
#  config:
#    type: nacos
#    nacos:
#      group: SEATA_GROUP
#      server-addr: localhost:8848
#      namespace:
#      username: nacos
#      password: nacos
#  registry:
#    type: nacos
#    nacos:
#      group: SEATA_GROUP
#      server-addr: localhost:8848
#      namespace:
#      username: nacos
#      password: nacos
