server:
  port: 18880
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://root:root@localhost:18880/eureka/

#security:
#  basic:
#    enabled: true
#  user:
#    name: root  #
#    password: root   #

